---
title: "Extraer conclusiones: Análisis de necesidades"
---

```{r options_communes, include=FALSE}
source("options_communes.R")
```


<div class="important">


- La recopilación de datos y los cuestionarios deben diseñarse en base a un plan de análisis (no al revés).
- Compartir información para contribuir a un análisis conjunto y a una comprensión común de la situación y las necesidades existentes.
</div>


Una vez finalizada la recolección y limpieza de los datos, comenzaremos con su análisis, el cual estará guiado por el marco analítico y el plan de análisis de datos.

El análisis de necesidades utiliza enfoques cualitativos y cuantitativos y la combinación de estos dependerá del propósito del ejercicio, la metodología de muestreo aplicada y sus limitaciones. Los objetivos principales de un análisis de necesidades son:

- Describir y entender la severidad de las condiciones de los grupos afectados incluyendo subgrupos de acuerdo con edad, género, otros factores de diversidad o localizaciones;
- Explicar asociaciones y factores subyacentes;
- Identificar y priorizar necesidades, vulnerabilidades y riesgos;
- Predecir la evolución del impacto de la crisis;
- Apoyar la definición y selección de las modalidades más adecuadas de respuesta.

Los principales pasos durante un análisis de necesidades se describen a continuación y son incrementales, cada uno está basado en el anterior:

## Paso 1. Describir

La descripción de datos consiste en determinar qué información nos pueden revelar los datos tanto cuantitativos, como cualitativos. Este proceso conlleva la agrupación de datos similares, y la agregación de múltiples valores en uno solo. Por ejemplo, el número de admisiones a un centro nutricional puede ser recolectado diariamente y agregado semanalmente.

Para el análisis de datos cuantitativos se utiliza estadística descriptiva básica, como la mediana, moda o media, la cual organiza, sintetiza y describe información de una manera fácil y rápida. Comúnmente emplea gráficos, cuadros y tablas para representar los valores y facilitar la comprensión de los datos.

Por otro lado, para el análisis de datos cualitativos se suelen utilizar categorías de análisis superior para agregar la información, por ejemplo, la gran mayoría de los informantes clave mencionaron crecientes enemistades e incidentes entre las personas refugiadas y migrantes, y las comunidades de acogida.

Una vez se han agregado los datos, estos se compararán para permitir la identificación de similitudes y diferencias entre una o más variables. Al realizar comparaciones, se podrán identificar tendencias, patrones, anomalidades o valores atípicos en los datos, proveyendo las bases para la identificación de información clave. Las comparaciones más utilizadas en los análisis de necesidades son:

- Comparaciones basadas en convenciones y estándares como Esfera, por ejemplo, comparar el estado nutricional medio de niñas y niños venezolanos menores de 5 años en Colombia, con estándares internaciones como Esfera. Si no están disponibles, se suelen utilizar valores de referencia como la media, por ejemplo, la media de acceso a medicinas antes y después de la crisis.
- Geográficas, comparaciones entre distintas provincias, o áreas donde el número de personas refugiadas y migrantes es mayor o menor. También pueden ser extendidas a otro tipo de elementos como el tipo de entorno, rural versus urbano, etc.
- Grupos socioeconómicos y otras comparaciones de diversidad para identificar los distintos niveles de necesidad entre grupos de población afectados.
- Sexo y edad, este tipo de comparaciones son esenciales en todas las evaluaciones de necesidades para entender las diferentes necesidades, prioridades y capacidades de hombres, mujeres, niños y niñas en grupos de edad y género clave.
- Comparaciones de tiempo se utilizan habitualmente como medidas intermedias para mostrar el impacto de la crisis o como medida de evolución de la respuesta.

Los principales resultados del análisis descriptivo incluyen:

- Los datos secundarios y primarios son agrupados y resumidos basándose en el plan de análisis de datos y categorías preidentificados de análisis, por ejemplo, entornos rurales versus urbanos, etc.
- Comparaciones de resultados basados en características relevantes como áreas geográficas, grupos de población afectados o tiempo, resaltando las similitudes y diferencias.
- Descripción de patrones clave, tendencias, anomalidades y valores atípicos.

_Ejemplo escenario: Después de completar con éxito la evaluación conjunta de necesidades multisectoriales que abarca los barrios "X, Y y Z" en los departamentos fronterizos de Colombia seleccionados, el equipo de evaluación está listo para analizar los resultados. En primer lugar, se hará una descripción de los datos recolectados:_

- __Proceso__: Después de la limpieza inicial de los datos de la encuesta de hogares, el analista de datos utiliza el software estadístico R para calcular las frecuencias y promedios básicos, por barrio y grupo de población encuestados. Al mismo tiempo, el analista de datos procesa los datos secundarios relevantes y los etiqueta por tiempo, barrio y grupo._
- __Resultado__: el 20% de la población encuestada informa que ha contraído deudas desde su llegada al país, principalmente de prestamistas informales. El 15% de estos hogares no tienen acceso a una fuente regular de ingresos. El 32% de la población de acogida en el barrio X han contraído deudas, en comparación con el 16% en el barrio Y. Es probable que los hogares de mayor tamaño hayan contraído más deudas. Los artículos de prensa informan que las tasas de interés promedio en el área de enfoque alcanzaron el 35%._

_Para más información sobre como describir datos y representarlos gráficamente:_

- **ACAPS,** [**Technical Brief: Compared to What. Analytical thinking and Needs assessment, 2013**](https://www.acaps.org/sites/acaps/files/resources/files/compared_to_what-analytical_thinking_and_needs_assessment_august_2013.pdf)
- **Financial Times,** [**Visual Vocabulary**](https://github.com/ft-interactive/chart-doctor/tree/master/visual-vocabulary)

## Paso 2. Explicar

Encontrar los problemas y los factores subyacentes que causan un determinado efecto, o entender por qué los problemas causan un efecto y no otro, puede ayudar a explicar por qué los datos dan lugar a ciertas conclusiones y no otras. El análisis exploratorio busca _asociaciones, correlaciones y en general conexiones entre observaciones y medidas_. Permite identificar los factores subyacentes basándose en una investigación exhaustiva de las relaciones, procesos y mecanismos causales.

Una **asociación** es cualquier relación, correspondencia, conexión o enlace entre dos o más variables de interés, cuya dependencia puede ser medida y verificada. Se puede decir que existe una asociación entre dos variables, cuando se mueven conjuntamente, pero ninguna de ellas influencia o causa la otra.

El termino asociación está relacionado con el termino correlación, y los dos implican que una o dos variables varían de acuerdo con un determinado patrón. De cualquier modo, la **correlación** está interesada principalmente en medir el grado por el cual la asociación de las variables se adhiere a un determinado patrón. La correlación es positiva cuando los valores incrementan conjuntamente y negativa cuando un valor incrementa y el otro decrementa. Es importante recordar que por que dos variables tengan una relación estadística, no quiere decir que una es responsable por causar, o por lo que causa la otra.

La **causalidad** es la relación entre la causa y el efecto, donde un factor causa el otro. Implica identificar la línea base, los eventos, procesos y otros factores intermedios, y los resultados finales, positivos o negativos.

Los principales resultados de la etapa de análisis exploratorio son:

- Asociaciones y correlaciones entre variables son detectadas y descritas.
- Factores contribuyentes y procesos subyacentes son descritos.
- Factores que mas contribuyen a los resultados son descritos.
- Explicaciones, hipótesis alternativas o rivales son desarrolladas.

_Ejemplo escenario: Una vez realizada la descripción de los datos, el equipo se dispone a explicar los resultados:_

- __Proceso__: Los resultados se discuten entre todos los miembros del equipo de evaluación y a continuación se consulta con un experto en medios de vida sobre los posibles factores subyacentes por los que se contraen deudas, mientras que un experto en protección revisa los posibles riesgos asociados con la eliminación de estas deudas._
- __Resultado__: Razones por las que se contraen deudas, por qué el barrio X tiene una mayor prevalencia, por qué los hogares de mayor tamaño tienen más probabilidades de haber contraído deudas. Riesgos de protección asociados con la deuda, especialmente para aquellos sin ingresos regulares._

## Paso 3. Interpretar

La interpretación de datos conlleva ir más allá de los datos y busca darles significado a través de contextualización, uso de la experiencia y selección de los hallazgos más importante que posibilitaran la toma de decisiones.

La interpretación exige un objetivo claro y un juicio analítico cuidadoso. A menudo los mismos datos pueden ser interpretados de diferentes maneras por diferentes analistas con diferentes niveles de experiencia, sesgos, suposiciones y áreas de enfoque. Para resolver este problema, es útil involucrar a otros socios y partes interesadas en el proceso de análisis, a través de ejercicios de análisis conjunto (ver sección 5.1.).

Fortalezas y limitaciones de las evidencias que respaldan las conclusiones y el razonamiento detrás de los juicios analíticos, deben evaluarse para detectar posibles fallas en argumentación y establecer la confiabilidad y credibilidad de las conclusiones. Las conclusiones derivadas de supuestos, en lugar de los datos disponibles deben señalarse claramente y comunicarse para evitar cualquier riesgo de interpretación errónea o acusaciones de parcialidad.

En los casos en que se ha utilizado una muestra aleatoria, la interpretación también implica determinar las condiciones y la medida en que los resultados pueden aplicarse a otros lugares, sectores humanitarios o grupos de población a través de una cuidadosa generalización y extrapolación.

Incorporar un análisis de género, edad y diversidad permite evitar generalizaciones o sesgos, e identificar las necesidades de manera diferenciada, de tal forma que se visibilice el impacto diferenciado y se mejore la pertinencia de los datos y la respuesta.

Finalmente, se deben proporcionar recomendaciones operativas sobre los problemas identificados como más severos y de mayor prioridad.

El siguiente es un conjunto de preguntas que se utilizan con frecuencia al interpretar datos de una evaluación de necesidades:

- ¿Qué se aprendió? ¿Cuáles son los resultados? ¿Qué se sabe sobre crisis pasadas y similares en la región, y ¿qué nos dice esto sobre los hallazgos actuales? ¿Son factibles?
- ¿Qué hay de nuevo, qué se esperaba y qué ha cambiado desde que comenzó la emergencia? ¿Qué ha permanecido igual cuando todo lo demás ha cambiado?, y ¿por qué la crisis lo cambió? ¿Qué resulta sorprendente? ¿Qué no es sorprendente y no necesita ser presentado o explicado en detalle? Si la situación para ciertos grupos o áreas no empeoraron, ¿por qué no?
- ¿Qué es importante o diferente sobre un grupo, tiempo o lugar en comparación con otro? ¿Son consistentes los patrones entre los diferentes grupos y fuentes de información? ¿Tienen sentido? ¿Cómo difiere un área geográfica de otra y por qué? ¿Qué difiere entre hombres y mujeres? ¿Qué tendencias se pueden observar?
- ¿Qué condiciones son las más severas? ¿Cuántas personas enfrentan esas condiciones?
- ¿Cuáles son los problemas o inquietudes más críticas que deben abordarse a corto, medio y a largo plazo?
- ¿Cuál es la fuente de la evidencia? ¿Qué tan creíbles son los hallazgos? ¿Cuáles son las limitaciones del análisis? ¿Podría el azar o el sesgo explicar los resultados? ¿Como se comparan los resultados con otros estudios? ¿Revelan los patrones señales significativas o simplemente representan el "ruido" en los datos? ¿Qué tan grande es la diferencia o cambio en condiciones y comportamiento? ¿Qué diferencias son más grandes que la imprecisión de lo medido?
- ¿Qué conclusiones se pueden sacar? ¿Cuáles son los mensajes más importantes? ¿Qué teorías o mecanismos podrían explicar estos hallazgos? ¿Qué hipótesis alternativas se puede sugerir?
- ¿Qué falta? ¿Cuál es el siguiente nivel de detalle requerido? ¿Dónde están las brechas de información que persisten? ¿Son esas brechas sobre problemas que no se comprenden bien y donde se necesita investigar? ¿Cuáles son los próximos pasos de investigación?

_Ejemplo escenario: Una vez explicadas las conclusiones iniciales, se interpretan los resultados y se realiza una priorización según la gravedad de la situación para los distintos grupos y barrios:_

- __Proceso__: Se realiza una sesión de análisis conjunto de 1 hora con 10 expertos de diferentes sectores y expertos geográficos. La sesión es facilitada por el equipo de evaluación._
- __Resultado__: Gravedad de la situación por barrios y grupos de población y selección de los grupos a priorizar._

_Para más información sobre cómo interpretar datos:_

- **ACAPS,** [**Technical brief: How Sure Are You? Judging Quality and Usability of Data Collected During Rapid Needs Assessments, 2013**](https://reliefweb.int/sites/reliefweb.int/files/resources/h-130827-tb-how-sure-are-you-final.pdf)
- **IASC,** [**Humanitarian Needs Overview Guidance, 2015**](https://reliefweb.int/sites/reliefweb.int/files/resources/hno_guidance_2015_final.pdf)

## Paso 4. Anticipar

El siguiente nivel en el análisis consiste en la anticipación de desarrollos futuros y prever posibles resultados y evolución de la situación actual, ya que los programas de respuesta se hacen un periodo de tiempo después de haber finalizado el análisis de datos, siendo por lo tanto posible que ciertas condiciones hayan cambiado.

Los pasos que se suelen tomar para anticipar posibles eventos futuros son:

- Utilizar datos históricos y tendencias para predecir cómo podría evolucionar la situación en el corto y mediano plazo, o si ya se ha producido un cambio desde que se recolectaron los datos. Se deberá considerar el impacto en las necesidades humanitarias y la habilidad para responder a las mismas si no hay cambios significativos en las tendencias.
- Identificar escenarios alternativos en los que podría evolucionar la situación.
- Validar escenarios en grupos durante talleres o reuniones, para evaluar su probabilidad y potencial impacto humanitario, basándose en juicios expertos y comparaciones a eventos similares ocurridos en el pasado.
- Monitorear la situación y comparar los resultados actuales con los resultados que se anticipan. Este paso es importante para mejorar los procedimientos de pronóstico, herramientas y suposiciones para su uso futuro.

_Ejemplo escenario: Finalmente, el equipo de evaluación hace un ejercicio para anticipar los posibles escenarios en los que puede evolucionar la situación actual y su impacto sobre los grupos de población:_

- __Proceso__: El equipo de evaluación organiza una sesión de análisis conjunto de 1,5 horas con 10 expertos y expertas de diferentes sectores, incluyendo geografía. La sesión es facilitada por el equipo de evaluación._
- __Resultado__: Se desarrollan tres escenarios sobre cómo podría evolucionar la situación en cuanto a medios de vida en los barrios X e Y en los próximos 6 meses, teniendo en cuenta el mercado laboral, la dinámica de desplazamiento y los mecanismos de supervivencia. Los escenarios incluyen el impacto de la situación en el acceso de la población a las necesidades básicas y problemas de protección._

_Para más información sobre como describir datos y representarlos gráficamente:_

- **ACAPS,** [**Technical brief: Scenario Building: How to Build Scenarios in Preparation for or During Humanitarian Crises, 2016**](https://www.acaps.org/sites/acaps/files/resources/files/acaps_technical_brief_scenario_building_august_2016.pdf)

